### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by PhilChodrow** [lu18cheng/pic16b_stock_analysis#1]
Hi Lu and Samuel, 

Overall, I think this is a good project proposal. It is *very* close to receiving credit. The only change I'd like you to make is for you to add more detail about what you are going to learn in the course of completing the project. In particular, you only mention time series analysis, when it seems to me that you will need to develop *many* more skills than that in order to complete the project, including database management, web development, and visualization, among other things. Please think this through a little more and add some more detail to this discussion. 

We aren't going to spend very much time on time series forecasting in this class, so you might benefit from starting your own research on the possibilities early. While it's possible to use TensorFlow or a similar general-purpose machine learning package, I'd instead suggest using something specialized for time series. Previous groups have had some success with the [prophet](https://github.com/facebook/prophet) package by Facebook. 

When you have made the requested revisions, please just reply to this issue. I'll see your reply and assess your revisions. 

I'm excited to see what you create!

**Comment by lu18cheng** [comment]
Hi Prof Chodrow,

Thank you for the feedback and the package recommendation! We’d made some changes on what we will learn and please let us know if there are anything else we should revise.

Best,
Lu
